import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({ component: Index });

const steps = [["01","Identifique o problema","Entenda exatamente o que o tema está pedindo."],["02","Encontre as causas","Pergunte por que o problema acontece."],["03","Escolha 2 argumentos","Defina os dois caminhos que vão sustentar sua tese."],["04","Selecione repertórios","Escolha referências que realmente tenham conexão."],["05","Monte sua tese","Organize seus dois argumentos em uma ideia clara."],["06","Escreva e revise","Transforme o plano em redação e confira antes de entregar."]];
const repertorios = [["Constituição Federal","Direitos sociais e dever do Estado","Cidadania, saúde, educação, desigualdade"],["Paulo Freire","Educação crítica e emancipação","Educação, desigualdade, exclusão"],["Zygmunt Bauman","Relações e sociedade na modernidade líquida","Tecnologia, consumo, relações sociais"],["Black Mirror","Impactos sociais e éticos da tecnologia","Tecnologia, comportamento, privacidade"],["Ailton Krenak","Relação entre sociedade e natureza","Meio ambiente, sustentabilidade, cultura"],["Carolina Maria de Jesus","Desigualdade e vulnerabilidade social","Pobreza, fome, desigualdade"]];
const dores = [["Travar na introdução","Você lê o tema, encara o papel e o primeiro parágrafo não sai."],["Repertório sem saber usar","Você conhece referências, mas não sabe se elas realmente combinam com o argumento."],["Argumentos rasos","Os parágrafos existem, mas acabam repetindo a mesma ideia."],["Conclusão genérica","A proposta fica vaga e não deixa claro quem vai agir, como e para quê."],["Medo de fugir do tema","A insegurança faz você gastar energia tentando adivinhar o que o corretor espera."],["Não saber o próximo passo","Você sabe que precisa escrever, mas não sabe o que decidir primeiro."]];
const features=[["01","Estrutura da redação","Entenda o papel da introdução, dos desenvolvimentos e da conclusão."],["02","Como criar uma tese","Tema → problema → dois argumentos → tese."],["03","Como desenvolver","Tópico frasal → explicação → repertório → conexão → consequência."],["04","Repertórios estratégicos","Referências com ideia central, temas e como conectar."],["05","Conclusão","Agente + ação + meio + finalidade + detalhamento."],["06","Checklist final","Revise tema, tese, argumentos, coesão e intervenção."]];
const faqs=[["Preciso saber escrever redação?","Não. O material foi pensado para quem ainda tem dificuldade em organizar a redação."],["É uma redação pronta para decorar?","Não. A proposta é ensinar um processo adaptável a diferentes temas."],["Vou aprender repertórios?","Sim. O guia apresenta referências e explica como relacioná-las aos argumentos."],["O guia garante nota 1000?","Não. O objetivo é ajudar você a organizar sua redação e desenvolver uma escrita mais consistente."],["Posso acessar pelo celular?","Sim. O material foi pensado para ser fácil de consultar durante os estudos."]];
function Book(){return <div className="bookWrap"><div className="book"><div className="bookKicker">GUIA DIGITAL</div><div><div className="bookTitle">REDAÇÃO<br/><strong>ENEM</strong></div><p>O Guia Estratégico para Subir Sua Nota</p></div><div className="bookRule"/><div className="bookMeta">Estrutura · Argumentação<br/>Repertório · Intervenção</div><div className="bookBadge">10 PÁGINAS</div></div></div>}
function CTA({secondary=false}:{secondary?:boolean}){return <a href="#oferta" className={secondary?"btn btnSecondary":"btn"}>{secondary?"Conhecer o guia":"QUERO MEU GUIA AGORA"}<span>→</span></a>}
function Index(){return <main>
<section className="hero darkSection"><nav className="nav container"><div className="brand">REDAÇÃO<span>ENEM</span></div><a href="#oferta" className="navLink">Quero meu guia</a></nav><div className="heroGrid container"><div><div className="eyebrow">GUIA ESTRATÉGICO · ENEM</div><h1>Recebeu o tema da redação e <em>não sabe por onde começar?</em></h1><p className="heroLead">Aprenda um passo a passo simples para sair do tema, encontrar seus argumentos, escolher seus repertórios e montar sua redação com mais segurança.</p><div className="heroCtas"><CTA/><span>Material digital · Acesso imediato</span></div></div><Book/></div><div className="flow container"><span>TEMA</span><b>→</b><span>PROBLEMA</span><b>→</b><span>ARGUMENTOS</span><b>→</b><span>REPERTÓRIOS</span><b>→</b><span>TESE</span><b>→</b><span>REDAÇÃO</span></div></section>
<section className="lightSection sectionPad"><div className="container narrow"><div className="eyebrow accent">SE ISSO ACONTECE COM VOCÊ</div><h2>O problema não é só escrever.<br/><em>É não saber o próximo passo.</em></h2><div className="painGrid">{dores.map(([t,d])=><div className="painCard" key={t}><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="darkSection sectionPad"><div className="container"><div className="center narrow"><div className="eyebrow lilac">A VIRADA</div><h2>Você tenta escrever antes de saber <em>o que vai dizer.</em></h2><p>Quando você organiza o raciocínio antes de escrever, a folha deixa de parecer um vazio.</p></div><div className="stepGrid">{steps.map(([n,t,d])=><article className="stepCard" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="lightSection sectionPad"><div className="container narrow"><div className="eyebrow accent">NA PRÁTICA</div><h2>Recebeu um tema.<br/><em>E agora?</em></h2><div className="exampleCard"><div><label>TEMA</label><h3>Desafios para combater a insegurança alimentar no Brasil</h3></div><div><label>PROBLEMA</label><p>Dificuldade de acesso à alimentação adequada.</p></div><div><label>ARGUMENTOS</label><p>Desigualdade socioeconômica.<br/>Insuficiência de políticas públicas.</p></div><div><label>REPERTÓRIO</label><p>Constituição Federal + Carolina Maria de Jesus.</p></div><div className="thesis"><label>TESE</label><p>A insegurança alimentar é agravada pela desigualdade socioeconômica e pela insuficiência das políticas públicas.</p></div></div><div className="note">💡 Perceba o caminho: tema → problema → argumentos → repertórios → tese.</div></div></section>
<section className="darkSection sectionPad"><div className="container"><div className="center narrow"><div className="eyebrow lilac">DENTRO DO GUIA</div><h2>Tudo o que você precisa para <em>parar de travar.</em></h2></div><div className="featureGrid">{features.map(([n,t,d])=><article className="featureCard" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="lightSection sectionPad"><div className="container narrow"><div className="eyebrow accent">REPERTÓRIO SEM DECORAÇÃO VAZIA</div><h2>Você não precisa de 100 citações.<br/><em>Precisa saber usar as certas.</em></h2><p className="sectionLead">O guia mostra a ideia central e como relacionar cada referência ao seu argumento.</p><div className="repGrid">{repertorios.map(([a,b,c])=><div className="repCard" key={a}><h3>{a}</h3><p><strong>Ideia:</strong> {b}</p><small>Possíveis temas: {c}</small></div>)}</div></div></section>
<section className="darkSection sectionPad"><div className="container honesty"><div><div className="eyebrow lilac">SEM PROMESSA MÁGICA</div><h2>Vamos ser <em>sinceros?</em></h2></div><div className="honestyCopy"><p>Este guia não vai escrever a redação por você.</p><p>Não existe repertório mágico que sirva perfeitamente para qualquer tema.</p><p>E nenhuma estrutura garante uma nota específica.</p><strong>O que ele faz é te dar clareza sobre o que fazer quando você recebe um tema.</strong></div></div></section>
<section className="lightSection sectionPad"><div className="container narrow"><div className="eyebrow accent">É PARA VOCÊ SE...</div><h2>Você quer mais <em>segurança</em> para escrever.</h2><div className="checks">{["Recebe o tema e não sabe como começar.","Tem dificuldade para criar uma tese.","Não sabe escolher bons argumentos.","Tem repertórios, mas não sabe encaixá-los.","Sente que seus parágrafos ficam genéricos.","Quer um roteiro simples para praticar."].map(x=><div key={x}><span>✓</span>{x}</div>)}</div></div></section>
<section id="oferta" className="offerSection"><div className="offerCard"><div className="eyebrow lilac">COMECE AGORA</div><h2>Redação ENEM:<br/><em>O Guia Estratégico</em></h2><p>O método prático para saber o que fazer quando receber um tema.</p><ul>{["E-book estratégico","Método de planejamento em 6 passos","Repertórios socioculturais","Estratégia de argumentação","Proposta de intervenção","Checklist de revisão","Conteúdos complementares"].map(x=><li key={x}>✓ {x}</li>)}</ul><div className="price"><small>POR APENAS</small><strong>[PREÇO]</strong></div><CTA/><small className="secure">Acesso digital · Compra segura</small></div></section>
<section className="lightSection sectionPad"><div className="container narrow honestyBox"><div className="eyebrow accent">SENDO HONESTO</div><h2>Este guia não promete <em>nota.</em></h2><p>Ele entrega um processo de planejamento e escrita para você aplicar, treinar e revisar com mais clareza.</p></div></section>
<section className="darkSection sectionPad"><div className="container author"><div className="avatar">FOTO</div><div><div className="eyebrow lilac">QUEM ESCREVEU</div><h2>[NOME DO CRIADOR]</h2><p>[BREVE APRESENTAÇÃO DO CRIADOR — preencher com informações reais.]</p></div></div></section>
<section className="lightSection sectionPad"><div className="container narrow"><div className="eyebrow accent">DÚVIDAS</div><h2>Perguntas <em>frequentes</em></h2><div className="faqList">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div className="bottomCta"><CTA secondary/></div></div></section>
<footer className="darkSection footer"><div className="container footerInner"><div><div className="brand">REDAÇÃO<span>ENEM</span></div><p>Um guia para você saber por onde começar.</p></div><small>Este material não possui vínculo com o INEP ou com o Ministério da Educação.<br/>© 2026 · Todos os direitos reservados.</small></div></footer>
</main>}
