import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css?v=20260829-6';
import './landing-overrides.css?v=20260829-1';

const steps=[['01','Identifique o problema','Entenda exatamente o que o tema está pedindo.'],['02','Encontre as causas','Pergunte por que o problema acontece.'],['03','Escolha 2 argumentos','Defina os dois caminhos que vão sustentar sua tese.'],['04','Selecione repertórios','Escolha referências que realmente tenham conexão.'],['05','Monte sua tese','Organize seus dois argumentos em uma ideia clara.'],['06','Escreva e revise','Transforme o plano em redação e confira antes de entregar.']];
const repertorios=[['Constituição Federal','Direitos sociais e dever do Estado','Cidadania, saúde, educação, desigualdade'],['Paulo Freire','Educação crítica e emancipação','Educação, desigualdade, exclusão'],['Zygmunt Bauman','Relações e sociedade na modernidade líquida','Tecnologia, consumo, relações sociais'],['Black Mirror','Impactos sociais e éticos da tecnologia','Tecnologia, comportamento, privacidade'],['Ailton Krenak','Relação entre sociedade e natureza','Meio ambiente, sustentabilidade, cultura'],['Carolina Maria de Jesus','Desigualdade e vulnerabilidade social','Pobreza, fome, desigualdade']];
const offerItems=[['E-book estratégico',14.90],['Método de planejamento em 6 passos',19.90],['Repertórios socioculturais',17.90],['Estratégia de argumentação',19.90],['Proposta de intervenção',14.90],['Checklist de revisão',9.90],['Conteúdos complementares',12.90]];
const formatBRL=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const IMG_STUDENT='/assets/student-editorial.svg'; const IMG_NOTEBOOK='/assets/notebook-editorial.svg'; const IMG_BOOKS='/assets/books-editorial.svg';
function App(){const[selected,setSelected]=useState<boolean[]>(offerItems.map(()=>true));const referenceTotal=useMemo(()=>offerItems.reduce((s,i)=>s+(i[1] as number),0),[]);const currentTotal=useMemo(()=>offerItems.reduce((s,i,n)=>s+(selected[n]?(i[1] as number):0),0),[selected]);const launchPrice=19.90;const savings=Math.max(currentTotal-launchPrice,0);const toggle=(n:number)=>setSelected(p=>p.map((v,i)=>i===n?!v:v));return <main>
<section className="hero"><nav><div className="logo">REDAÇÃO<span>ENEM</span></div><a href="#oferta">Quero meu guia</a></nav><div className="heroGrid"><div><div className="eyebrow">GUIA ESTRATÉGICO • ENEM</div><h1>Recebeu o tema da redação e <em>não sabe por onde começar?</em></h1><p className="lead">Aprenda um passo a passo simples para sair do tema, encontrar seus argumentos, escolher seus repertórios e montar sua redação com mais segurança.</p><button onClick={()=>document.getElementById('oferta')?.scrollIntoView({behavior:'smooth'})}>QUERO APRENDER O MÉTODO <span>→</span></button><small>Material digital • Acesso imediato</small></div><div className="heroVisual"><img className="heroPhoto" src={IMG_STUDENT} alt="Estudante estudando para o ENEM"/><div className="book"><div className="bookTop">REDAÇÃO<br/><strong>ENEM</strong></div><div className="bookTitle">O GUIA<br/>ESTRATÉGICO</div><div className="bookLine"/><p>Estrutura • Argumentação<br/>Repertório • Intervenção</p><div className="bookBadge">10 PÁGINAS</div></div></div></div><div className="flow"><b>TEMA</b><span>→</span><b>PROBLEMA</b><span>→</span><b>ARGUMENTOS</b><span>→</span><b>REPERTÓRIOS</b><span>→</span><b>TESE</b><span>→</span><b>REDAÇÃO</b></div></section>
<section className="light identification"><div className="splitEditorial"><div className="sectionHead"><div className="eyebrow">SE ISSO ACONTECE COM VOCÊ</div><h2>O problema não é só escrever.<br/><em>É não saber o próximo passo.</em></h2></div><div className="editorialImage"><img src={IMG_NOTEBOOK} alt="Caderno e materiais de estudo"/><span>ANTES DE ESCREVER<br/><b>ORGANIZE O RACIOCÍNIO.</b></span></div></div><div className="painGrid">{['“Eu leio o tema várias vezes e continuo sem saber o que escrever.”','“Tenho repertório, mas nunca sei se ele combina com o tema.”','“Meus argumentos parecem muito genéricos.”','“Na conclusão eu nunca sei o que colocar.”','“Tenho medo de fugir do tema.”','“Começo a introdução e travo.”'].map(x=><div className="pain" key={x}>{x}</div>)}</div></section>
<section className="dark diagnosis"><div className="center"><div className="eyebrow">A VIRADA</div><h2>Você tenta escrever antes de saber <em>o que vai dizer.</em></h2><p>Quando você organiza o raciocínio antes de escrever, a folha deixa de parecer um vazio.</p></div><div className="process">{steps.map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="light practical"><div className="sectionHead"><div className="eyebrow">NA PRÁTICA</div><h2>Recebeu um tema.<br/><em>E agora?</em></h2></div><div className="example"><div><label>TEMA</label><h3>Desafios para combater a insegurança alimentar no Brasil</h3></div><div className="mini"><label>PROBLEMA</label><p>Dificuldade de acesso à alimentação adequada.</p></div><div className="mini"><label>ARGUMENTOS</label><p>Desigualdade socioeconômica.<br/>Insuficiência de políticas públicas.</p></div><div className="mini"><label>REPERTÓRIO</label><p>Constituição Federal + Carolina Maria de Jesus.</p></div><div className="thesis"><label>TESE</label><p>A insegurança alimentar é agravada pela desigualdade socioeconômica e pela insuficiência das políticas públicas.</p></div></div><p className="note">💡 Perceba o caminho: tema → problema → argumentos → repertórios → tese.</p></section>
<section className="dark contents"><div className="contentsIntro"><div className="center"><div className="eyebrow">DENTRO DO GUIA</div><h2>Tudo o que você precisa para <em>parar de travar.</em></h2></div><img src={IMG_BOOKS} alt="Livros e materiais de estudo"/></div><div className="cards">{[['01','Estrutura da redação','Entenda o papel da introdução, dos desenvolvimentos e da conclusão.'],['02','Como criar uma tese','Tema → problema → dois argumentos → tese.'],['03','Como desenvolver','Tópico frasal → explicação → repertório → conexão → consequência.'],['04','Repertórios estratégicos','Referências com ideia central, temas e como conectar.'],['05','Conclusão','Agente + ação + meio + finalidade + detalhamento.'],['06','Checklist final','Revise tema, tese, argumentos, coesão e intervenção.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="light repertory"><div className="sectionHead"><div className="eyebrow">REPERTÓRIO SEM DECORAÇÃO VAZIA</div><h2>Você não precisa de 100 citações.<br/><em>Precisa saber usar as certas.</em></h2><p>O guia mostra a ideia central e como relacionar cada referência ao seu argumento.</p></div><div className="repGrid">{repertorios.map(([a,b,c])=><div className="rep" key={a}><h3>{a}</h3><p><b>Ideia:</b> {b}</p><small>Possíveis temas: {c}</small></div>)}</div></section>
<section className="dark honesty"><div className="honestyInner"><div><div className="eyebrow">SEM PROMESSA MÁGICA</div><h2>Vamos ser <em>sinceros?</em></h2></div><div className="honestyVisual"><img src={IMG_STUDENT} alt="Estudante em preparação"/><div><p>Este guia não vai escrever a redação por você.</p><p>Não existe repertório mágico que sirva perfeitamente para qualquer tema.</p><p>E nenhuma estrutura garante uma nota específica.</p><strong>O que ele faz é te dar clareza sobre o que fazer quando você recebe um tema.</strong></div></div></div></section>
<section className="light audience"><div className="sectionHead"><div className="eyebrow">É PARA VOCÊ SE...</div><h2>Você quer mais <em>segurança</em> para escrever.</h2></div><div className="checks">{['Recebe o tema e não sabe como começar.','Tem dificuldade para criar uma tese.','Não sabe escolher bons argumentos.','Tem repertórios, mas não sabe encaixá-los.','Sente que seus parágrafos ficam genéricos.','Quer um roteiro simples para praticar.'].map(x=><div key={x}>✓ <span>{x}</span></div>)}</div></section>
<section id="oferta" className="offer"><div className="offerCard"><div className="offerVisual"><img src={IMG_BOOKS} alt="Materiais de estudo"/><div className="book offerBook"><div className="bookTop">REDAÇÃO<br/><strong>ENEM</strong></div><div className="bookTitle">O GUIA<br/>ESTRATÉGICO</div><div className="bookLine"/><p>Estrutura • Argumentação<br/>Repertório • Intervenção</p><div className="bookBadge">10 PÁGINAS</div></div></div><div className="eyebrow">CONDIÇÃO DE LANÇAMENTO</div><h2>Você não precisa aprender tudo de uma vez.<br/><em>Precisa saber o próximo passo.</em></h2><p className="offerSub">O Guia Estratégico organiza o caminho entre receber o tema e começar a escrever.</p><div className="offerGrid"><div><ul>{offerItems.map(([name,value],i)=><li key={name} className={selected[i]?'selected':''} onClick={()=>toggle(i)}><span className="check">{selected[i]?'✓':'+'}</span><span>{name}</span><b>{formatBRL(value as number)}</b></li>)}</ul><small className="calcNote">Valores exibidos são referências da composição do pacote, não preços de venda separados.</small></div><div className="calculator"><div className="calcLabel">CALCULADORA DO PACOTE</div><p className="calcTitle">Monte seu pacote e veja a referência.</p><div className="calcRow"><span>Valor de referência</span><strong>{formatBRL(currentTotal)}</strong></div><div className="calcRow highlight"><span>Condição de lançamento</span><strong>{formatBRL(launchPrice)}</strong></div><div className="save">Você economiza <b>{formatBRL(savings)}</b></div><button>QUERO MEU GUIA AGORA <span>→</span></button><small className="secure">Acesso digital • Compra segura</small></div></div><small className="referenceTotal">Pacote completo: {formatBRL(referenceTotal)} em valor de referência.</small></div></section>
<section className="faq light"><div className="sectionHead"><div className="eyebrow">DÚVIDAS</div><h2>Perguntas <em>frequentes</em></h2></div><div className="faqList">{[['Preciso saber escrever redação?','Não. O material foi pensado para quem ainda tem dificuldade em organizar a redação.'],['É uma redação pronta para decorar?','Não. A proposta é ensinar um processo adaptável a diferentes temas.'],['Vou aprender repertórios?','Sim. O guia apresenta referências e, principalmente, explica como relacioná-las aos argumentos.'],['O guia garante nota 1000?','Não. O objetivo é ajudar você a organizar sua redação e desenvolver uma escrita mais consistente.'],['Posso acessar pelo celular?','Sim. O material foi pensado para ser fácil de consultar durante os estudos.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<footer><div className="logo">REDAÇÃO<span>ENEM</span></div><p>Um guia para você saber por onde começar.</p><small>© 2026 • Todos os direitos reservados.</small></footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);
